name: ImagePull&Push

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1

      - name: docker hub auth
        uses: docker/login-action@v3.3.0
        with:
          username: ${{secrets.DOCKERUSER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: build docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            laranjeirajuliano/agilstore:${{github.run_number}}
            laranjeirajuliano/agilstore:latest